import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {
  AiFillTwitterCircle, 
  AiFillLinkedin, 
  AiFillYoutube} 
from 'react-icons/ai';
import Image from 'next/image';
import deved from "../public/dev-ed-wave.png"
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from  "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode? 'dark': ''} >
      <Head>
        <title>Tognia Henri Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
          <h1 className='text-xl font-burtons dark:text-gray-200'>Developed By TNH</h1>
          <ul className='flex items-center'>
            <li>
              <BsFillMoonStarsFill onClick={()=>{setDarkMode(!darkMode)}} className='cursor-pointer text-2xl dark:text-gray-200'/>
            </li>
            <li><a className= 'bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a></li>
          </ul>
          </nav>   
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>TOGNIA Henri</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-gray-200'>Developer and designer</h3>
            <p className='text-md py-5 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-200'>
            With these steps, you have manually created an IAM role in AWS with the necessary permissions and configured 
            GitHub Actions to use that role for deployment. The secret credentials (AWS access key ID and secret access key) 
            are not exposed in the workflow, and the workflow will use the specified IAM role and region for deploying the API Gateway API.
            </p>
          </div> 
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillYoutube />
          </div>  
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 
                          rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
              <Image src={deved} layout='fill' objectFit='cover'  />
          </div>      
        </section>

        <section className='dark:text-gray-200'>
          <div>
            <h3 className='text-3xl py-1'>Service I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
            Si tu me montres là où on dit les parents que vous trouvez intéressants tu as gagné. 
            <span className='text-teal-500'>
              Agencies
            </span> consulted for 
            <span className='text-teal-500'>
              Startup
            </span>
            We collaborated with talented people to provide you our committed client best quality offer
            services so that we can deserve the confidence you put in us
            </p>
            <p className='text-md leading-8 text-gray-800 dark:text-gray-200'>
              I offer a wide range of services for businesses and particular in need
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
                  <Image className='relative mx-auto' src={design} width={100} height={100}  />
                  <h3 className='text-lg font-medium pt-8 pb'>Beautiful design</h3>
                  <p className='py-2'>We create beautiful design that will shine your compan to the world</p>
                  <h4 className='py-4 text-teal-600'>Design Tools I use</h4>
                  <p className='text-gray-800 py-1'>Photoshop</p>
                  <p className='text-gray-800 py-1'>Illustrator</p>
                  <p className='text-gray-800 py-1'>Figma</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
                  <Image className='relative mx-auto' src={consulting} width={100} height={100}  />
                  <h3 className='text-lg font-medium pt-8 pb'>Consulting</h3>
                  <p className='py-2'>We create beautiful design that will shine your compan to the world</p>
                  <h4 className='py-4 text-teal-600'>Design Tools I use</h4>
                  <p className='text-gray-800 py-1'>Photoshop</p>
                  <p className='text-gray-800 py-1'>Illustrator</p>
                  <p className='text-gray-800 py-1'>Figma</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
                  <Image className='relative mx-auto' src={code} width={100} height={100}  />
                  <h3 className='text-lg font-medium pt-8 pb'>Code</h3>
                  <p className='py-2'>We create beautiful design that will shine your compan to the world</p>
                  <h4 className='py-4 text-teal-600'>Design Tools I use</h4>
                  <p className='text-gray-800 py-1'>Photoshop</p>
                  <p className='text-gray-800 py-1'>Illustrator</p>
                  <p className='text-gray-800 py-1'>Figma</p>
            </div>
          </div>
        </section>
        <section>
          <div className='dark:text-gray-200'>
            <h3 className='text-3xl py-1'>Portofolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
            Si tu me montres là où on dit les parents que vous trouvez intéressants tu as gagné. 
            <span className='text-teal-500'>
              Agencies
            </span> consulted for 
            <span className='text-teal-500'>
              Startup
            </span>
            We collaborated with talented people to provide you our committed client best quality offer
            services so that we can deserve the confidence you put in us
            </p>
            <p className='text-md leading-8 text-gray-800 dark:text-gray-200'>
              I offer a wide range of services for businesses and particular in need
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={web1} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web4} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web5} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web6} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
