import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {
  AiFillTwitterCircle, 
  AiFillLinkedin, 
  AiFillYoutube} 
from 'react-icons/ai';
import Image from 'next/image';
import deved from "../public/dev-ed-wave.png"
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tognia Henri Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
          <h1 className='text-xl font-burtons'>Developed By TNH</h1>
          <ul className='flex items-center'>
            <li>
              <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
            </li>
            <li><a className= 'bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a></li>
          </ul>
          </nav>   
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>TOGNIA Henri</h2>
            <h3 className='text-2xl py-2'>Developer and designer</h3>
            <p className='text-md py-5 text-gray-800'>
            With these steps, you have manually created an IAM role in AWS with the necessary permissions and configured 
            GitHub Actions to use that role for deployment. The secret credentials (AWS access key ID and secret access key) 
            are not exposed in the workflow, and the workflow will use the specified IAM role and region for deploying the API Gateway API.
            </p>
          </div> 
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillYoutube />
          </div>  
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
              <Image src={deved} layout='fill' objectFit='cover'  />
          </div>      
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1'>Service I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>
            Si tu me montres là où on dit les parents que vous trouvez intéressants tu as gagné. 
            <span className='text-teal-500'>
              Agencies
            </span> consulted for 
            <span className='text-teal-500'>
              Startup
            </span>
            We collaborated with talented people to provide you our committed client best quality offer
            services so that we can deserve the confidence you put in us
            </p>
            <p className='text-md leading-8 text-gray-800'>
              I offer a wide range of services for businesses and particular in need
            </p>
          </div>
          <div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
                  <Image className='relative mx-auto' src={design} width={100} height={100}  />
                  <h3 className='text-lg font-medium pt-8 pb'>Beautiful design</h3>
                  <p className='py-2'>We create beautiful design that will shine your compan to the world</p>
                  <h4 className='py-4 text-teal-600'>Design Tools I use</h4>
                  <p className='text-gray-800 py-1'>Photoshop</p>
                  <p className='text-gray-800 py-1'>Illustrator</p>
                  <p className='text-gray-800 py-1'>Figma</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
                  <Image className='relative mx-auto' src={consulting} width={100} height={100}  />
                  <h3 className='text-lg font-medium pt-8 pb'>Consulting</h3>
                  <p className='py-2'>We create beautiful design that will shine your compan to the world</p>
                  <h4 className='py-4 text-teal-600'>Design Tools I use</h4>
                  <p className='text-gray-800 py-1'>Photoshop</p>
                  <p className='text-gray-800 py-1'>Illustrator</p>
                  <p className='text-gray-800 py-1'>Figma</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
                  <Image className='relative mx-auto' src={code} width={100} height={100}  />
                  <h3 className='text-lg font-medium pt-8 pb'>Code</h3>
                  <p className='py-2'>We create beautiful design that will shine your compan to the world</p>
                  <h4 className='py-4 text-teal-600'>Design Tools I use</h4>
                  <p className='text-gray-800 py-1'>Photoshop</p>
                  <p className='text-gray-800 py-1'>Illustrator</p>
                  <p className='text-gray-800 py-1'>Figma</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>Portofolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>
            Si tu me montres là où on dit les parents que vous trouvez intéressants tu as gagné. 
            <span className='text-teal-500'>
              Agencies
            </span> consulted for 
            <span className='text-teal-500'>
              Startup
            </span>
            We collaborated with talented people to provide you our committed client best quality offer
            services so that we can deserve the confidence you put in us
            </p>
            <p className='text-md leading-8 text-gray-800'>
              I offer a wide range of services for businesses and particular in need
            </p>
          </div>
        </section>
      </main>
    </>
  )
}
